name: CI

on: pull_request

jobs:
  flutter_test:
    name: Run Flutter Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Flutter Version
        run: flutter --version
      - name: Flutter pub get
        run: flutter pub get
      - name: Flutter analyze
        run: flutter analyze --no-fatal-infos